### PR TITLE
Update freetype path and fix for breaking changes.

### LINKED ISSUE #150: Please export freetype-go to github
Google Code will be turning read-only on August 25th. Would you  export freetype-go to github , and change "code.google.com/p/freetype-go"  to  "github.com/*/freetype-go" ?

### LINKED ISSUE #155: question  freetype didn't findit
cannot find package   "code.google.com/p/freetype-go/freetype/truetype" in any of:
         /usr/lib/go/src/pkg/code.google.com/p/freetype-go/freetype/truetype (from $GOROOT)
          /home/belr/Goprogram/vendor/src/code.google.com/p/freetype-go/freetype/truetype (from $GOPATH)
        /home/belr/Goprogram/src/code.google.com/p/freetype-go/freetype/truetype

### PR DESCRIPTION
**Pull request by ben-clayton**
Fixes #155
Fixes #150

### CODE REVIEW

File: drivers/gl/glyph_page.go [hunk 1]
```diff
@@ -136,25 +96,10 @@ func (p *glyphPage) add(rune rune, g *glyph) bool {
...
-	}
-
-	// Perform the rasterization
-	a := &image.Alpha{
-		Pix:    p.image.Pix[x+y*p.image.Stride:],
-		Stride: p.image.Stride,
-		Rect:   image.Rect(0, 0, w, h),
-	}
-	p.rast.Rasterize(raster.NewAlphaSrcPainter(a))
+	_, _, mask, maskp, _ := face.Glyph(fixed.Point26_6{}, r)
```
Comment (nigeltao) [inline drivers/gl/glyph_page.go]: BTW, you'll need to make another (simple) change for
https://github.com/golang/freetype/commit/03bdcc0fe1c41fb81c28f5ad739241c1f0b6ec9b

_, _, mask, maskp, _
would become
_, mask, maskp, _, _

Sorry.

Comment (ben-clayton) [inline drivers/gl/glyph_page.go]: Done. Thanks for the heads up.
